import type { Icon } from "@phosphor-icons/react";
import {
  BlueprintIcon,
  BriefcaseIcon,
  ChartLineUpIcon,
  ChatCircleIcon,
  CheckSquareIcon,
  ClipboardTextIcon,
  ClockIcon,
  CreditCardIcon,
  CubeIcon,
  DatabaseIcon,
  FileTextIcon,
  FlowArrowIcon,
  GearIcon,
  GitPullRequestIcon,
  GitBranchIcon,
  GraphIcon,
  HouseIcon,
  KanbanIcon,
  LightbulbIcon,
  ListChecksIcon,
  MagnifyingGlassIcon,
  MapTrifoldIcon,
  PackageIcon,
  PaintBrushIcon,
  PathIcon,
  PlugIcon,
  PresentationChartIcon,
  RocketLaunchIcon,
  ShapesIcon,
  SquaresFourIcon,
  StackIcon,
  TargetIcon,
  TestTubeIcon,
  TreeStructureIcon,
  UserIcon,
  UsersThreeIcon,
  WrenchIcon,
} from "@phosphor-icons/react";

export const NAV_ICONS: Record<string, Icon> = {
  home: HouseIcon,
  tasks: ListChecksIcon,
  workflow_instructions: FlowArrowIcon,
  chat: ChatCircleIcon,
  connections: PlugIcon,
  schedules: ClockIcon,
  executive: BriefcaseIcon,
  research: MagnifyingGlassIcon,
  product: PackageIcon,
  manager: RocketLaunchIcon,
  workflow_map: GraphIcon,
  executive_roadmap: MapTrifoldIcon,
  executive_goals: TargetIcon,
  research_market: ChartLineUpIcon,
  research_user: UsersThreeIcon,
  research_hypotheses: LightbulbIcon,
  product_initiatives: RocketLaunchIcon,
  manager_initiatives: RocketLaunchIcon,
  development: CubeIcon,
  design: PaintBrushIcon,
  dev_data_model: DatabaseIcon,
  dev_system_model: TreeStructureIcon,
  dev_api_reference: FileTextIcon,
  dev_integration: FlowArrowIcon,
  design_ia: TreeStructureIcon,
  design_ui_components: ShapesIcon,
  design_theme: PaintBrushIcon,
  design_toolchain: WrenchIcon,
  initiative_overview: SquaresFourIcon,
  planning_prd: ClipboardTextIcon,
  planning_features: StackIcon,
  planning_stories: FileTextIcon,
  design_wireframes: PresentationChartIcon,
  design_flows: PathIcon,
  architecture_spec: CubeIcon,
  architecture_data: DatabaseIcon,
  architecture_integration: FlowArrowIcon,
  build_plan: KanbanIcon,
  build_tasks: CheckSquareIcon,
  build_pull_requests: GitPullRequestIcon,
  qa_test_plan: TestTubeIcon,
  launch_plan: RocketLaunchIcon,
  launch_docs: FileTextIcon,
  retro_metrics: ChartLineUpIcon,
  retro_review: GitBranchIcon,
  developer_setup: WrenchIcon,
  settings: GearIcon,
  billing: CreditCardIcon,
  settings_general: GearIcon,
  settings_account: UserIcon,
  settings_appearance: PaintBrushIcon,
  settings_members: UsersThreeIcon,
  settings_teamspace: CubeIcon,
};

export function NavItemIcon({
  iconKey,
  className,
}: {
  iconKey: string;
  className?: string;
}) {
  const IconComponent = NAV_ICONS[iconKey];
  if (!IconComponent) return <span className="size-4 shrink-0" aria-hidden />;
  return <IconComponent className={className ?? "size-4 shrink-0"} aria-hidden />;
}
