import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const instructionsDir = join(root, "src/agents/workflows/instructions");
const outFile = join(root, "src/agents/workflows/instruction-bodies.ts");

const files = readdirSync(instructionsDir).filter((name) => name.endsWith(".md"));
const entries = files.map((filename) => {
  const body = readFileSync(join(instructionsDir, filename), "utf8");
  return `  ${JSON.stringify(filename)}: ${JSON.stringify(body)},`;
});

const source = `// Generated by scripts/embed-workflow-instructions.ts — do not edit manually.
export const INSTRUCTION_BODIES: Record<string, string> = {
${entries.join("\n")}
};
`;

writeFileSync(outFile, source);
console.log(`Wrote ${outFile} (${files.length} instructions)`);
