packages:
  - "apps/*"
  - "packages/*"
  - "e2e"
allowBuilds:
  '@swc/core': true
  cbor-extract: true
  esbuild: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@supabase/auth-js@2.108.1'
  - '@supabase/functions-js@2.108.1'
  - '@supabase/postgrest-js@2.108.1'
  - '@supabase/realtime-js@2.108.1'
  - '@supabase/storage-js@2.108.1'
  - '@supabase/supabase-js@2.108.1'
