packages:
  - "apps/*"
  - "packages/*"
  - "e2e"
overrides:
  "@types/react": "19.2.17"
  "@types/react-dom": "19.2.3"
allowBuilds:
  '@sentry/cli': true
  '@swc/core': true
  bufferutil: false
  cbor-extract: true
  esbuild: true
  sharp: true
  unrs-resolver: true
  utf-8-validate: false
  zlib-sync: false
minimumReleaseAgeExclude:
  - '@supabase/auth-js@2.108.1'
  - '@supabase/functions-js@2.108.1'
  - '@supabase/postgrest-js@2.108.1'
  - '@supabase/realtime-js@2.108.1'
  - '@supabase/storage-js@2.108.1'
  - '@supabase/supabase-js@2.108.1'
  - '@vercel/oidc@3.6.2'
  - emulate@0.8.0
